name: Compilar Kernel Note 20 Ultra

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar base de CyberInfintyKernel
        run: |
          git clone -b RAGNARØK https://github.com/dav-quez/CyberInfintyKernel.git fuente-kernel

      - name: Instalar dependencias de Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools ccache wget gcc-aarch64-linux-gnu git

      - name: Desactivar KernelSU en Kconfig (Evita el Error)
        run: |
          cd fuente-kernel
          sed -i '/kernelsu\/Kconfig/s/^/#/' drivers/Kconfig
          echo "Línea de KernelSU desactivada para evitar bloqueos en el build."

      - name: Corregir Ruta Térmica de la GPU (Fix gpex_thermal)
        run: |
          cd fuente-kernel
          echo "Creando parches de rutas para el compilador..."
          # Forzamos la creación de la ruta que el Makefile de la GPU espera encontrar
          mkdir -p drivers/gpu/arm/exynos/frontend
          cp drivers/gpu/arm/exynos/frontend/gpex_thermal.c drivers/gpu/arm/bv_r38p1/gpex_thermal.c 2>/dev/null || true
          # Enlazamos de forma absoluta para blindar el sub-make
          ln -s /home/runner/work/InfintyKernel/InfintyKernel/fuente-kernel/drivers/gpu/arm/exynos /home/runner/work/InfintyKernel/InfintyKernel/fuente-kernel/drivers/gpu/arm/exynos

      - name: Inyectar u Optimizar Overclock
        run: |
          cd fuente-kernel
          mkdir -p drivers/cpufreq
          echo "Descargando e inyectando controladores ACME modificados..."
          wget -O drivers/cpufreq/exynos-acme.c https://raw.githubusercontent.com/dav-quez/CyberInfintyKernel/RAGNAR%C3%98K/drivers/cpufreq/exynos-acme.c
          wget -O drivers/cpufreq/exynos-acme.h https://raw.githubusercontent.com/dav-quez/CyberInfintyKernel/RAGNAR%C3%98K/drivers/cpufreq/exynos-acme.h

      - name: Iniciar Compilación del Kernel
        run: |
          cd fuente-kernel
          chmod +x ./build.sh
          ./build.sh -m c1s -k y

      - name: Subir Kernel Flasheable
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Overclock-C2S
          path: fuente-kernel/*.zip
